Repository Fingerstyle-Taiwan/django-backend, pull requests merged in 2022-10, with the labels that each got.

#14 Add production setup
  Makefile
  docker-compose-deploy.yml
  proxy/Dockerfile
  proxy/default.conf.tpl
  proxy/run.sh
  proxy/uwsgi_params
  requirements.txt
  scripts/run.sh
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#15 Add production setup
  Makefile
  docker-compose-deploy.yml
  proxy/Dockerfile
  proxy/default.conf.tpl
  proxy/run.sh
  proxy/uwsgi_params
  requirements.txt
  scripts/run.sh
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#16 fix(Dockerfile): Add command to run script
  Dockerfile
Labels: HACKTOBERFEST-ACCEPTED

#17 fix(Dockerfile): Fix typo at ENV path
  Dockerfile
Labels: HACKTOBERFEST-ACCEPTED

#20 refactor(default.conf.tpl): Change locaiton for django service
  proxy/default.conf.tpl
Labels: HACKTOBERFEST-ACCEPTED

#22 Update to main
  .gitignore
  Makefile
  app/app/urls.py
  docker-compose-deploy.yml
  proxy/default.conf.tpl
Labels: HACKTOBERFEST-ACCEPTED

#27 Request contest model
  app/app/urls.py
  app/contest/__init__.py
  app/contest/apps.py
  app/contest/migrations/__init__.py
  app/contest/serializers.py
  app/contest/urls.py
  app/contest/views.py
  app/core/migrations/0008_contest.py
  app/core/models.py
Labels: enhancement

#35 Add contest model
  app/app/urls.py
  app/contest/__init__.py
  app/contest/apps.py
  app/contest/migrations/__init__.py
  app/contest/serializers.py
  app/contest/urls.py
  app/contest/views.py
  app/core/migrations/0008_contest.py
  app/core/models.py
Labels: enhancement

#37 Add contest model
  .env.sample
  app/app/settings.py
  app/contest/migrations/__init__.py
  app/contest/serializers.py
  app/core/admin.py
  app/core/migrations/0001_initial.py
  app/core/migrations/0002_alter_profile_user.py
  app/core/migrations/0003_alter_user_options_remove_user_created_at.py
  app/core/migrations/0004_alter_user_options.py
  app/core/migrations/0005_alter_user_options.py
  app/core/migrations/0006_delete_profile.py
  app/core/migrations/0007_profile.py
  app/core/migrations/0008_artist.py
  app/core/models.py
  docker-compose-deploy.yml
  docker-compose.yml
Labels: enhancement, HACKTOBERFEST-ACCEPTED
